name: Build KaidenMod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential git

    - name: Clone Geode SDK (latest stable)
      run: |
        git clone --branch stable https://github.com/geode-sdk/geode.git

    - name: Build Geode Mod
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: KaidenMod
        path: build
}
